apiVersion: v1
kind: Namespace
metadata:
  name: exact
---
apiVersion: v1
kind: Service
metadata:
  name: exact
  namespace: exact
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: exact
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exact
  namespace: exact
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exact
  template:
    metadata:
      labels:
        app: exact
    spec:
      containers:
        - name: exact
          image: nginx
          ports:
            - containerPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: exact
  namespace: exact
spec:
  ingressClassName: nginx
  rules:
    - host: foo.com
      http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name: exact
                port:
                  number: 80
