apiVersion: v1
kind: Namespace
metadata:
  name: prefix
---
apiVersion: v1
kind: Service
metadata:
  name: prefix
  namespace: prefix
spec:
  ports:
    - port: 80
      targetPort: 5678
  selector:
    app: prefix
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prefix
  namespace: prefix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prefix
  template:
    metadata:
      labels:
        app: prefix
    spec:
      containers:
        - name: prefix
          image: hashicorp/http-echo
          ports:
            - containerPort: 5678
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prefix
  namespace: prefix
spec:
  ingressClassName: nginx
  rules:
    - host: foo.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prefix
                port:
                  number: 80
